#!/usr/bin/env bash

set -eu

cd /etc/letsencrypt/live/halx.fzbx.io/

cp fullchain.pem /etc/one/fullchain.pem
cp privkey.pem /etc/one/privkey.pem

chown -R oneadmin:oneadmin /etc/one/fullchain.pem
chown -R oneadmin:oneadmin /etc/one/privkey.pem

/usr/sbin/service opennebula-novnc restart
